In [57]:
import numpy as np
import pandas as pd

In [58]:
ratings = pd.read_csv(
    "data/u.data",
    sep="\t",
    names=[
        "user_id",
        "movie_id",
        "rating",
        "timestamp"
    ]
)

ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [59]:
users = pd.read_csv(
    "data/u.user",
    sep="|",
    names=[
        "user_id",
        "age",
        "gender",
        "occupation",
        "zip_code"
    ],
    encoding="latin-1"
)

users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [60]:
genre_names = [
    "unknown",
    "Action",
    "Adventure",
    "Animation",
    "Children",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Fantasy",
    "Film-Noir",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Thriller",
    "War",
    "Western"
]

movie_columns = [
    "movie_id",
    "title",
    "release_date",
    "video_release",
    "imdb_url"
] + genre_names

movies = pd.read_csv(
    "data/u.item",
    sep="|",
    names=movie_columns,
    encoding="latin-1"
)

movies.head()

,movie_id,title,release_date,video_release,imdb_url,unknown,Action,Adventure,Animation,Children,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [61]:
df = ratings.merge(
    users,
    on="user_id"
).merge(
    movies,
    on="movie_id"
)

df.head()

,user_id,movie_id,rating,timestamp,age,gender,occupation,zip_code,title,release_date,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,196,242,3,881250949,49,M,writer,55105,Kolya (1996),24-Jan-1997,...,0,0,0,0,0,0,0,0,0,0
1,186,302,3,891717742,39,F,executive,00000,L.A. Confidential (1997),01-Jan-1997,...,0,1,0,0,1,0,0,1,0,0
2,22,377,1,878887116,25,M,writer,40206,Heavyweights (1994),01-Jan-1994,...,0,0,0,0,0,0,0,0,0,0
3,244,51,2,880606923,28,M,technician,80525,Legends of the Fall (1994),01-Jan-1994,...,0,0,0,0,0,1,0,0,1,1
4,166,346,1,886397596,47,M,educator,55113,Jackie Brown (1997),01-Jan-1997,...,0,0,0,0,0,0,0,0,0,0

In [62]:
df.columns

Index(['user_id', 'movie_id', 'rating', 'timestamp', 'age', 'gender',
       'occupation', 'zip_code', 'title', 'release_date', 'video_release',
       'imdb_url', 'unknown', 'Action', 'Adventure', 'Animation', 'Children',
       'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir',
       'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War',
       'Western'],
      dtype='str')

In [63]:
df.describe()

,user_id,movie_id,rating,timestamp,age,video_release,unknown,Action,Adventure,Animation,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
count,100000.00000,100000.000000,100000.000000,1.000000e+05,100000.000000,0.0,100000.0000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.00000,100000.000000,100000.000000
mean,462.48475,425.530130,3.529860,8.835289e+08,32.969850,NaN,0.0001,0.255890,0.137530,0.036050,...,0.013520,0.017330,0.053170,0.049540,0.052450,0.194610,0.12730,0.21872,0.093980,0.018540
std,266.61442,330.798356,1.125674,5.343856e+06,11.562623,NaN,0.0100,0.436362,0.344408,0.186416,...,0.115487,0.130498,0.224373,0.216994,0.222934,0.395902,0.33331,0.41338,0.291802,0.134894
min,1.00000,1.000000,1.000000,8.747247e+08,7.000000,NaN,0.0000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000
25%,254.00000,175.000000,3.000000,8.794487e+08,24.000000,NaN,0.0000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000
50%,447.00000,322.000000,4.000000,8.828269e+08,30.000000,NaN,0.0000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000
75%,682.00000,631.000000,4.000000,8.882600e+08,40.000000,NaN,0.0000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000
max,943.00000,1682.000000,5.000000,8.932866e+08,73.000000,NaN,1.0000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 31 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   user_id        100000 non-null  int64
 1   movie_id       100000 non-null  int64
 2   rating         100000 non-null  int64
 3   timestamp      100000 non-null  int64
 4   age            100000 non-null  int64
 5   gender         100000 non-null  str
 6   occupation     100000 non-null  str
 7   zip_code       100000 non-null  str
 8   title          100000 non-null  str
 9   release_date   99991 non-null   str
 10  video_release  0 non-null       float64
 11  imdb_url       99987 non-null   str
 12  unknown        100000 non-null  int64
 13  Action         100000 non-null  int64
 14  Adventure      100000 non-null  int64
 15  Animation      100000 non-null  int64
 16  Children       100000 non-null  int64
 17  Comedy         100000 non-null  int64
 18  Crime          100000 non-null  int64
 19  Documentary    100000 non-null  int64
 20  Drama          100000 non-null  int64
 21  Fantasy        100000 non-null  int64
 22  Film-Noir      100000 non-null  int64
 23  Horror         100000 non-null  int64
 24  Musical        100000 non-null  int64
 25  Mystery        100000 non-null  int64
 26  Romance        100000 non-null  int64
 27  Sci-Fi         100000 non-null  int64
 28  Thriller       100000 non-null  int64
 29  War            100000 non-null  int64
 30  Western        100000 non-null  int64
dtypes: float64(1), int64(24), str(6)
memory usage: 23.7 MB

In [81]:
column_names = [
    "user_id",
    "movie_id",
    "rating",
    "timestamp"
]

train = pd.read_csv(
    "data/u1.base",
    sep="\t",
    names=column_names
)

test = pd.read_csv(
    "data/u1.test",
    sep="\t",
    names=column_names
)

In [82]:
train_df = (
    train
    .merge(users, on="user_id")
    .merge(movies, on="movie_id")
)

In [65]:
bins = [0, 18, 25, 35, 45, 50, 60, 100]

labels = [
    "0-18",
    "19-25",
    "26-35",
    "36-45",
    "46-50",
    "51-60",
    "60+"
]

df["age_group"] = pd.cut(
    df["age"],
    bins=bins,
    labels=labels
)
df[
    ["age", "age_group"]
].head()

   age age_group
0   49     46-50
1   39     36-45
2   25     19-25
3   28     26-35
4   47     46-50

In [66]:
feature_to_idx = {}

feature_counter = 0

genre_columns = [
    "unknown",
    "Action",
    "Adventure",
    "Animation",
    "Children",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Fantasy",
    "Film-Noir",
    "Horror",
    "Musical",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Thriller",
    "War",
    "Western"
]

for _, row in df.iterrows():

    features = [
        f"user_{row['user_id']}",
        f"movie_{row['movie_id']}",
        f"gender_{row['gender']}",
        f"occupation_{row['occupation']}",
        f"age_{row['age_group']}"
    ]

    # Add genres
    for genre in genre_columns:

        if row[genre] == 1:
            features.append(
                f"genre_{genre}"
            )

    # Build feature dictionary
    for feature in features:

        if feature not in feature_to_idx:

            feature_to_idx[feature] = feature_counter
            feature_counter += 1

In [67]:
print("Total Features:", len(feature_to_idx))

Total Features: 2674

In [68]:
training_samples = []

for _, row in df.iterrows():

    feature_indices = [

        feature_to_idx[f"user_{row['user_id']}"],

        feature_to_idx[f"movie_{row['movie_id']}"],

        feature_to_idx[f"gender_{row['gender']}"],

        feature_to_idx[f"occupation_{row['occupation']}"],

        feature_to_idx[f"age_{row['age_group']}"]

    ]

    # Genres
    for genre in genre_columns:

        if row[genre] == 1:

            feature_indices.append(
                feature_to_idx[
                    f"genre_{genre}"
                ]
            )

    training_samples.append(
        (
            feature_indices,
            row["rating"]
        )
    )

In [69]:
len(training_samples)

100000

In [70]:
training_samples[0]

([0, 1, 2, 3, 4, 5], 3)

In [76]:
class FactorizationMachine:

    def __init__(
        self,
        num_features,
        user_features,
        movie_features,
        k=20,
        learning_rate=0.01,
        reg=0.02
    ):

        self.num_features = num_features
        
        self.user_features = user_features
        self.movie_features = movie_features
        
        self.k = k

        self.learning_rate = learning_rate
        self.reg = reg

        # Global Bias
        self.w0 = 0.0

        # Linear Weights
        self.w = np.zeros(num_features)

        # Feature Embeddings
        self.V = np.random.normal(
            0,
            0.01,
            (num_features, k)
        )
    
    
    def predict(
    self,
    feature_indices
    ):
    
        prediction = self.w0
    
        # Linear Part
        for feature in feature_indices:
        
            prediction += self.w[
                feature
            ]
    
        # Interaction Part
        interaction = 0.0
    
        for f in range(self.k):
        
            sum1 = 0.0
            sum2 = 0.0
    
            for feature in feature_indices:
            
                value = self.V[
                    feature,
                    f
                ]
    
                sum1 += value
                sum2 += value * value
    
            interaction += 0.5 * (
                sum1 * sum1 - sum2
            )
    
        prediction += interaction
    
        prediction = np.clip(
            prediction,
            1,
            5
        )
    
        return prediction
    

    def sgd_step(
        self,
        feature_indices,
        rating
    ):

        prediction = self.predict(
            feature_indices
        )

        error = rating - prediction

        # Global bias
        self.w0 += (
            self.learning_rate * error
        )

        # Linear weights
        for feature in feature_indices:

            self.w[feature] += (
                self.learning_rate
                * (
                    error
                    -
                    self.reg
                    * self.w[feature]
                )
            )

        # Sum of embeddings
        sum_v = np.zeros(self.k)

        for feature in feature_indices:

            sum_v += self.V[feature]

        # Update embeddings
        for feature in feature_indices:

            gradient = (
                sum_v
                -
                self.V[feature]
            )

            self.V[feature] += (

                self.learning_rate
                * (
                    error * gradient

                    -

                    self.reg
                    * self.V[feature]
                )

            )

        return error

    def fit(
        self,
        training_samples,
        epochs=20
    ):
    
        print("Training Factorization Machine...")
    
        for epoch in range(epochs):
        
            np.random.shuffle(
                training_samples
            )
    
            squared_errors = []
    
            for feature_indices, rating in training_samples:
            
                error = self.sgd_step(
                    feature_indices,
                    rating
                )
    
                squared_errors.append(
                    error ** 2
                )
    
            rmse = np.sqrt(
                np.mean(
                    squared_errors
                )
            )
    
            print(
                f"Epoch {epoch+1:2d}/{epochs}"
                f" | RMSE = {rmse:.4f}"
            )    

    def build_feature_vector(
        self,
        user_id,
        movie_id
    ):

        return (
            self.user_features[user_id]
            +
            self.movie_features[movie_id]
        )


    def predict_rating(
        self,
        user_id,
        movie_id
    ):

        feature_indices = self.build_feature_vector(
            user_id,
            movie_id
        )

        return self.predict(
            feature_indices
        )


    def evaluate(
        self,
        test_df
    ):

        predictions = []

        squared_errors = []

        absolute_errors = []

        for row in test_df.itertuples(index=False):

            if (
                row.user_id not in self.user_features
                or
                row.movie_id not in self.movie_features
            ):
                continue

            predicted = self.predict_rating(
                row.user_id,
                row.movie_id
            )

            error = abs(
                row.rating - predicted
            )

            predictions.append(
                (
                    row.user_id,
                    row.movie_id,
                    row.rating,
                    predicted,
                    error
                )
            )

            absolute_errors.append(error)
            squared_errors.append(error**2)

        prediction_df = pd.DataFrame(
            predictions,
            columns=[
                "user_id",
                "movie_id",
                "actual",
                "predicted",
                "error"
            ]
        )

        mae = np.mean(
            absolute_errors
        )

        rmse = np.sqrt(
            np.mean(
                squared_errors
            )
        )

        return prediction_df, rmse, mae


    def recommend(
        self,
        user_id,
        train_df,
        top_n=10
    ):

        watched = set(

            train_df.loc[
                train_df.user_id == user_id,
                "movie_id"
            ]

        )

        recommendations = []

        for movie_id in self.movie_features:

            if movie_id in watched:
                continue

            prediction = self.predict_rating(
                user_id,
                movie_id
            )

            recommendations.append(
                (
                    movie_id,
                    prediction
                )
            )

        recommendations.sort(
            key=lambda x: x[1],
            reverse=True
        )

        return pd.DataFrame(
            recommendations[:top_n],
            columns=[
                "movie_id",
                "predicted_rating"
            ]
        )

In [77]:
user_features = {}

for _, row in users.iterrows():

    age_group = pd.cut(
        [row["age"]],
        bins=[0,18,25,35,45,50,60,100],
        labels=[
            "0-18",
            "19-25",
            "26-35",
            "36-45",
            "46-50",
            "51-60",
            "60+"
        ]
    )[0]

    user_features[row["user_id"]] = [

        feature_to_idx[f"user_{row['user_id']}"],

        feature_to_idx[f"gender_{row['gender']}"],

        feature_to_idx[f"occupation_{row['occupation']}"],

        feature_to_idx[f"age_{age_group}"]

    ]

In [78]:
movie_features = {}

genre_columns = movies.columns[5:]

for _, row in movies.iterrows():

    features = [

        feature_to_idx[
            f"movie_{row['movie_id']}"
        ]

    ]

    for genre in genre_columns:

        if row[genre] == 1:

            features.append(
                feature_to_idx[
                    f"genre_{genre}"
                ]
            )

    movie_features[row["movie_id"]] = features

In [79]:
fm = FactorizationMachine(
    num_features=len(feature_to_idx),
    user_features=user_features,
    movie_features=movie_features,
    k=20
)

fm.fit(
    training_samples,
    epochs=20
)

Training Factorization Machine...
Epoch  1/20 | RMSE = 1.0137
Epoch  2/20 | RMSE = 0.9567
Epoch  3/20 | RMSE = 0.9398
Epoch  4/20 | RMSE = 0.9268
Epoch  5/20 | RMSE = 0.9153
Epoch  6/20 | RMSE = 0.9047
Epoch  7/20 | RMSE = 0.8948
Epoch  8/20 | RMSE = 0.8847
Epoch  9/20 | RMSE = 0.8760
Epoch 10/20 | RMSE = 0.8672
Epoch 11/20 | RMSE = 0.8595
Epoch 12/20 | RMSE = 0.8527
Epoch 13/20 | RMSE = 0.8434
Epoch 14/20 | RMSE = 0.8367
Epoch 15/20 | RMSE = 0.8294
Epoch 16/20 | RMSE = 0.8224
Epoch 17/20 | RMSE = 0.8145
Epoch 18/20 | RMSE = 0.8083
Epoch 19/20 | RMSE = 0.8008
Epoch 20/20 | RMSE = 0.7952

In [80]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(
    ratings,
    test_size=0.2,
    random_state=42
)
train = pd.read_csv(
    "data/u1.base",
    sep="\t",
    names=[
        "user_id",
        "movie_id",
        "rating",
        "timestamp"
    ]
)

test = pd.read_csv(
    "data/u1.test",
    sep="\t",
    names=[
        "user_id",
        "movie_id",
        "rating",
        "timestamp"
    ]
)

In [ ]:
prediction_df, rmse, mae = fm.evaluate(test)

print("MAE :", mae)
print("RMSE:", rmse)

In [73]:
sample, rating = training_samples[10]

print("Actual:", rating)

print(
    "Prediction:",
    fm.predict(sample)
)

Actual: 5
Prediction: 4.931409194641247